<a href="https://colab.research.google.com/github/aditi-tawade-ai/SkillBuilding/blob/main/Python_Practice/Py_Random_Que.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q. natural nos from 1 to n
n = 10
num = 1
while num<=n:
  print(num)
  num+=1

1
2
3
4
5
6
7
8
9
10

In [ ]:
n = 10
num = 1
for n in range(1,11):
  print(n)
  n +=1

1
2
3
4
5
6
7
8
9
10

In [ ]:
# reverse
n = 1
num = 10
while num>=n:
  print(num)
  num-=1

10
9
8
7
6
5
4
3
2
1

In [ ]:
n = 1
num = 10
for n in range(10,0,-1):
  print(n)

10
9
8
7
6
5
4
3
2
1

In [ ]:
# sum of 1st 10 num
n = 1
sum = 0
while n<=10:
  sum = sum+n
  n+=1
print(sum)

55

In [ ]:
n = 1
sum = 0
for n in range(1,11):
  sum = sum+n
print(sum)

55

In [ ]:
# multiplicatn table
n = int(input('Enter a number:'))
i = 1
while i in range(1,11):
  mul = n*i
  print(n,'x',i,'=',mul)
  i+=1

Enter a number:5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

In [ ]:
# password inp until correct
pas = 1234
ps = int(input('enter password:'))
#for p in ps:
if ps==pas:
   print(' correct password')
    #break
else:
    print('enter correct password')
    #break

enter password:1234
 correct password

In [ ]:
pas = 1234
# ps = int(input('enter password:'))
while ps!=pas:
  ps = int(input('enter password:'))
if ps==pas:
   print('correct password')

enter password:145
enter password:785
enter password:1234
correct password

In [ ]:
# ask for name and if types exit then stop
data = input('enter your name:')
while data!='exit':
  print('hello',data)
  data = input('enter your name:')
print('exit')

enter your name:adi
hello adi
enter your name:sayee
hello sayee
enter your name:exit
exit

In [ ]:
# enter marks or 0 for calculatn
mks = int(input('enter marks:'))
sum = 0
while mks!=0:
  sum = sum+mks
  mks = int(input('enter marks:'))
print('sum of marks:',sum)

enter marks:10
enter marks:20
enter marks:50
enter marks:0
sum of marks: 80

In [ ]:
# greater no. between 2
a = int(input('en4ter a number:'))
b = int(input('enter second num:'))
if a>b:
  print(a,'is greater than',b)
else:
  print(b,'is greater than',a)

enter a number:23
enter second num:5
23 is greater than 5

In [ ]:
# check+ve,-ve or 0
n = int(input('enter a number:'))
if n>0:
  print(n,'is positive')
elif n<0:
  print(n,'is negative')
else:
  print('it is a zero')

enter a number:0
it is a zero

In [ ]:
# num divisible by 5 and 11
num = [10,55,21,155,110,45]
y = []
N = []
for n in num:
 if n%5==0 and n%11==0:
  y.append(n)
  #print(y,'are divisible by 5 and 11')
 else:
  N.append(n)
  #print(N,'are not divisible')
print(y,'are divisible by 5 and 11')
print(N,'are not divisible')

[55, 110] are divisible by 5 and 11
[10, 21, 155, 45] are not divisible

In [ ]:
# check leap year or not
year = int(input('enter a year:'))
if year%4==0:
  print(year,'is a leap year')
elif year%400==0:
  print(year,'is a leap year')
elif year%100==0:
  print(year,'is not a leap year')
else:
  print(year,'is not a leap year')

enter a year:2028
2028 is a leap year

In [ ]:
# wether a alphabet or not
char = input('enter a character:')
if char.isalpha():
  print(char,'is an alphabet')
else:
  print(char,'is not an alphabet')

enter a character:5
5 is not an alphabet

In [ ]:
char = input('enter a character:')
for c in char:
  if (char>='a' and char<='z') or (char>='A' and char<='Z'):
    print(char,'is an alphabet')
    break
  else:
    print(char,'is not an alphabet')
    break

enter a character:5
5 is not an alphabet

In [ ]:
from typing import dataclass_transform
# count total no. of notes in given amount
#amt = 10000
amount = int(input('enter amount:'))
deno = [500,200,100,50,20,10,5,2,1]
for d in deno:
  notes = amount//d
  remaining_amount = amount % d
  if notes>0:
    print(d,':',notes)
  amount = remaining_amount

enter amount:6542
500 : 13
20 : 2
2 : 1

In [ ]:
a = ['ai','','do','eat','']
b = [n for n in a if n != '']
b

['ai', 'do', 'eat']

In [ ]:
a = ['ai',['step'],'do',['eat'],'go']
b = [i for n in a for i in (n if type(n)==list else [n])]
b

['ai', 'step', 'do', 'eat', 'go']

In [ ]:
k = [120,1,90,66,9]
lr = sorted(k)
lr[-2]

90

In [ ]:
s = "ABC PQR"
#expected output: "CBA RQP"
s = "ABC","PQR"
for n in s:
 rev = s[::-1]
print(rev)

('PQR', 'ABC')

In [ ]:
# important
s = "ABC PQR"
output = " ".join(word[::-1] for word in s.split())
print(output)

CBA RQP

In [ ]:
s = 'arya musale'
s = s.lower()
s = s.replace(' ','')
v_count = 0
c_count = 0
vowels = 'aeiou'
for n in s:
  if n.isalpha():
    if n in vowels:
      v_count+=1
    else:
      c_count+=1
print('vowels count:',v_count)
print('consonent count',c_count)

vowels count: 5
consonent count 5

In [ ]:
for i in range(1,7):
  for j in range(i):
    print('*',end = '')
  print()

*
**
***
****
*****
******

In [ ]:
for i in range(1,7):
  for j in range(i):
    print(chr(i+64),end ='')
  print()

A
BB
CCC
DDDD
EEEEE
FFFFFF

In [ ]:
num=int(input('enter a number:'))
i = 1
fact = 1
while i<=num:
  fact = fact*i
  i+=1
print(fact)

enter a number:3
6

In [ ]:
# prime numbers
num = int(input('Enter a number:'))

if num<=1:
    print(num, 'is a prime number')
for n in range(2,num):
  if num % n == 0:
    print(num,'is not a prime number')
    break
  else:
    print(num,'is a prime number')
    break

Enter a number:7
7 is a prime number

In [ ]:
# even or odd
num = int(input('Enter a number:'))
if num%2==0:
  print('It is a even number')
else:
  print('It is a odd number')

Enter a number:8
It is a even number

In [ ]:
# sort list of tuple on 2nd value using lambda
a = [('AI',6),('No',2),('Yes',4),('Hi',5),('Bye',1),('ok',3)]
b = sorted(a,key = lambda x:x[1])
print(b)

[('Bye', 1), ('No', 2), ('ok', 3), ('Yes', 4), ('Hi', 5), ('AI', 6)]

In [ ]:
# Sort employee records based on salary list od dict
emp = [{'Om':96000},
       {'Sai':25000},
       {'Shree':45000},
       {'Jui':89000},
       {'maya':1500}]
a = sorted(emp,key=lambda x:list(x.values()))
a

[{'maya': 1500},
 {'Sai': 25000},
 {'Shree': 45000},
 {'Jui': 89000},
 {'Om': 96000}]

In [ ]:
# Write a program that handles ValueError and ZeroDivisionError separately.
a = 10
try:
  b = int(input('enter a number:'))
  print('Result:',a/b)
except ValueError:
  print('Error occured:please enter a valid number')
except ZeroDivisionError:
  print('Error occured: Denominator cannot be zero')

enter a number:a
Error occured:please enter a valid number

In [ ]:
# Write a program that raises an exception if the number is negative.
num = int(input('Enter a number:'))
try:
  if num < 0:
    raise ValueError('Number cannot be negative')
    print('Number is:',num)
  else:
    print('Number is:',num)
except ValueError as e:
  print(e)

Enter a number:-78
Number cannot be negative

In [ ]:
# Write a program to open a file safely using exception handling.
try:
  file = open('file.txt','r')
  print(file.read())
  file.close()
except FileNotFoundError:
  print('File not found')

File not found

In [ ]:
# Write a program showing how finally is used for cleanup.
try:
  a = (input('enter a 4 digit pin:'))
  if not a.isdigit():
   raise ValueError('Pin should not be a alphabetic word')
  print('Your pin is:',a)
except ValueError as e:
  print(e)
finally:
  print('Thank you')

enter a 4 digit pin:lkj
Pin should not be a alphabetic word
Thank you

In [ ]:
# accept students detail using **kwargs
def details(**info):
  print(info)
details(Om=1, sai = 2, shree = 3, jay = 4)

{'Om': 1, 'sai': 2, 'shree': 3, 'jay': 4}

In [ ]:
# fun to add n no. of values
def add(*num):
  total = 0
  for n in num:
    total = total+n
  print(total)
add(10,52,48,63,200)

373

In [ ]:
# op of one function is passed as input to other function
def mks(score):
  if score<35:
    return 'fail'
  else:
    return 'pass'
def per(st):
  if st=='pass':
    print('you passed the exam')
  else:
    print('you failed the exam')
mk = int(input('enter makrs:'))
res = mks(mk)
per(res)

enter makrs:12
you failed the exam

In [ ]:
# Select even numbers from a list and then square them.
num = [25,14,22,36,39,89,85,13]
evn = list(filter(lambda x:x%2==0,num))
sq = list(map(lambda x:x**2,evn))
print(evn)
print(sq)

[14, 22, 36]
[196, 484, 1296]

In [ ]:
#Add corresponding elements of two lists using map().
a = [10,20,30]
b = [21,36,78]
add = list(map(lambda x,y:x+y,a,b))
print(add)

[31, 56, 108]

In [ ]:
#  Remove empty strings from a list using filter().
nm = ['ai','go','','yes','','no','']
new = list(filter(lambda x:x!='',nm))
print(new)

['ai', 'go', 'yes', 'no']

In [ ]:
# Filter names whose length is greater than 5 characters.
nm = ['Ai','Python','string','ice','bottle','walk']
new = list(filter(lambda x:len(x)>5,nm))
new

['Python', 'string', 'bottle']

In [ ]:
# Use reduce() to find the sum of all numbers in a list.
from functools import reduce
a = [1,2,3,4,5,6,7,8,9]
mul = reduce(lambda x,y:x*y,a)
print(mul)

362880

In [ ]:
# Find the largest number from a list using reduce().
a = [26,87,96,21,102,136,45]
lr = reduce(lambda x,y: x if x>y else y, a)
lr

136

In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
import pandas as pd
path = '/content/banknotes (1).csv'
df = pd.read_csv(path)
df[:6]

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0
5   4.36840    9.6718   -3.9606 -3.16250      0

In [ ]:
df.columns

Index(['Variance', 'Skewness', 'Curtosis', 'Entropy', 'Class'], dtype='object')

In [ ]:
df.shape

(1372, 5)

In [ ]:
df.loc[:2]

   Variance  Skewness  Curtosis  Entropy  Class
0    3.6216    8.6661   -2.8073 -0.44699      0
1    4.5459    8.1674   -2.4586 -1.46210      0
2    3.8660   -2.6383    1.9242  0.10645      0

In [ ]:
df.iloc[3]

Variance    3.4566
Skewness    9.5228
Curtosis   -4.0112
Entropy    -3.5944
Class       0.0000
Name: 3, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Variance  1372 non-null   float64
 1   Skewness  1372 non-null   float64
 2   Curtosis  1372 non-null   float64
 3   Entropy   1372 non-null   float64
 4   Class     1372 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB